#!/bin/bash

g() {
  GIT_TERMINAL_PROMPT=0 git "$@"
}

create_key() {
  echo "Creating ssh key..." && \
  local manufacturer="$(getprop ro.product.manufacturer)" && \
  local model="$(getprop ro.product.model)" && \
  yes | pkg install openssh termux-api && \
  local key="${HOME}/.ssh/id_ed25519" && \
  rm -f "${key}" "${key}.pub" && \
  mkdir -p "${HOME}/.ssh" && \
  yes "" | ssh-keygen -t ed25519 \
    -C "${manufacturer} ${model} termux" \
    -f "${key}" -N "" && \
  echo && \
  echo && \
  echo "Public ssh key has been copied to clipboard." && \
  echo "Now you have to add it to GitHub" && \
  echo && \
  echo "[Press enter to open GitHub]" && \
  
  
  termux-open-url 'https://github.com/settings/keys' && \
  
}

yes | pkg install git && {
  [[ -d "${HOME}/.git" ]] || {
    rm -rf "${HOME}/*" && \
    git clone https://falouu@github.com/falouu/android-termux.git "${HOME}"
  } && \
  cd "${HOME}" && \
  g remote update origin || {
    echo "Fixing access to the repository..." && \
    create_key && \
    g remote update origin && \
    g pull
  }


  # if [[ -f "${HOME}/.ssh"
}
