#!/bin/bash

set -o errexit,pipefail

yes | pkg install git && {
  [[ -d "${HOME}/.git" ]] || {
    rm -rf "${HOME}/*" && \
    git clone https://falouu@github.com/falouu/android-termux.git "${HOME}"
  }
}
